server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fcfs_arcade
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    #    hibernate ddl auto ?? ??? ??
    #   generate-ddl: true
    #    ?? : https://ykh6242.tistory.com/102
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true # ?????? sql? ?? ?? ??
        globally_quoted_identifiers: true #???? ??? ??? RDBMS? ???? ??? ??? ???? ??? ??
    hibernate:
      ddl-auto: none
      # none: ???? ???? ??? (???? DB?? ?????)
      # create-drop: SessionFactory? ??? ? drop? ??? ????, SessionFactory? ??? ? drop? ???? (in-memory DB? ?? ?????)
      # create: SessionFactory? ??? ? ?????? drop? ???? ??? DDL? ????
      # update: ??? ???? ????
      # validate: ??? ???? ??? ???? ???? ??????? ????
  #session:
  #  store-type: jdbc
scheduler:
  process-interval: 3000
  process-data: 50