server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fcfs_arcade
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    #    hibernate ddl auto 설정 활성화 여부
    #   generate-ddl: true
    #    참고 : https://ykh6242.tistory.com/102
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true # # 하이버네이트 sql문 포맷 정렬 여부
        globally_quoted_identifiers: true #컬럼이나 테이블 이름이 RDBMS의 예약어인 경우를 고려해 따옴표로 감싸서 생성
    hibernate:
      ddl-auto: none
      # none: 아무것도 실행하지 않는다 (대부분의 DB에서 기본값이다)
      # create-drop: SessionFactory가 시작될 때 drop및 생성을 실행하고, SessionFactory가 종료될 때 drop을 실행한다 (in-memory DB의 경우 기본값이다)
      # create: SessionFactory가 시작될 때 데이터베이스 drop을 실행하고 생성된 DDL을 실행한다
      # update: 변경된 스키마를 적용한다
      # validate: 변경된 스키마가 있다면 변경점을 출력하고 애플리케이션을 종료한다
  #session:
  #  store-type: jdbc
scheduler:
  process-period: 3000
  process-size: 5